### PR TITLE
support docker-sync for mac users

### PR DESCRIPTION
**Pull request by hoffmannkrzysztof**
[//]: # (Thank you for helping us out: your efforts mean great deal to the project and the community as a whole!)

[//]: # (Before you proceed:)

[//]: # (1. Make sure to add yourself to `CONTRIBUTORS.rst` through this PR provided you're contributing here for the first time)
[//]: # (2. Don't forget to update the `docs/` presuming others would benefit from a concise description of whatever that you're proposing)

## Description

[//]: # (What's it you're proposing?)

Every mac users suffer using docker on their macs. Sharing files through containers is very slow.

## Rationale

[//]: # (Why does the project need that?)

Only mac users need this. Other users don't care :)

## Use case(s) / visualization(s)

[//]: # ("Better to see something once than to hear about it a thousand times.")

If you are using many static files in containers loading speed of each request decrease.

### CODE REVIEW

**Comment by webyneter** [comment]
@hoffmannkrzysztof could the `delegated` flag facilitate in healing that wound somehow?

**Comment by hoffmannkrzysztof** [comment]
@webyneter I not sure if I understand you clearly. But docker-sync helps a lot of users who using mac while developing. Take a look at the official documentation: http://docker-sync.io/. I am using this solution and see only pros.

**Comment by sfdye** [comment]
> Every mac users suffer using docker on their macs

1. I am a Mac & Docker user. I didn't experience any slowness whatsoever with sharing files from docker containers. How could you reproduce exactly?

2. `docker-sync` seems to [support](https://github.com/EugenMayer/docker-sync/wiki/1.-Installation) windows/linux as well, why not support them?

3. Shouldn't it be an optional feature, for added complexity?

**Comment by hoffmannkrzysztof** [comment]
@sfdye 
1. This issue on mac is related to a large number of I/O operations. The easy way to reproduce this issue is by using a large number of assets. Take a look for more info: https://github.com/docker/for-mac/issues/77 
2. Of course, docker-sync support Windows and Linux and can be used. 
3. This addon is optional. If you don't want sync when you will use regular docker-compose

**Comment by elyak123** [comment]
I used to have that same issue until I started using `docker-machine`, try it, is worth the shot.

**Comment by browniebroke** [comment]
Docker for mac has improved the file sharing implementation with VirtuoFS:

https://www.docker.com/blog/speed-boost-achievement-unlocked-on-docker-desktop-4-6-for-mac/

In my experience it's much faster, so I'm closing this, I consider it no longer needed.

**Pull request closed without merging**
