### PR TITLE
Move navbar to the right

### PR DESCRIPTION
**Pull request by reyesvicente**
move nav links to the right

## Description

Checklist:

- [x] I've made sure that tests are updated accordingly (especially if adding or updating a template option)
- [x] I've updated the documentation or confirm that my change doesn't require any updates

## Rationale

Just moved the nav links to the right.

### CODE REVIEW

**Comment by foarsitter** [comment]
@reyesvicente what is the reason behind this PR? Can you provide some more context?

**Comment by browniebroke** [comment]
I too don't see value in merging this, this is a subjective cosmetic tweak, and folks would be 50-50 to get what we currently have vs what is suggested. So wihtout a clear reason, keep it as is.

**Comment by reyesvicente** [comment]
> @reyesvicente what is the reason behind this PR? Can you provide some more context?

I don't understand why it's in the left in the first place. Normally, navlinks are at the right side of the page.

**Comment by browniebroke** [comment]
No clear benefits, so priority to keep it as is. Thanks for the suggestion.

**Pull request closed without merging**
