### PR TITLE
Upgrade to django 4.2

### PR DESCRIPTION
**Pull request by foarsitter**
According to the magnificant table of https://github.com/cookiecutter/cookiecutter-django/issues/4252 we are ready to update to Django 4.2.

### CODE REVIEW

**Comment by browniebroke** [comment]
We might want to waait for the [next DRF version](https://github.com/encode/django-rest-framework/pull/8794) (3.15) which seems imminent now.

**Comment by foarsitter** [comment]
@browniebroke there is indeed a comment stating 4.2.1 is compatible. DRF is waiting for a release for several months now so hopefully it will be there soon.

**Comment by Andrew-Chen-Wang** [comment]
@browniebroke It seems like DRF 3.14 supports Django 4.1, or at least definitely with 4.2 given auvipy's comment. I think it's safe to merge

**Comment by browniebroke** [comment]
Agree. I've since updated one of my projects using DRF and can confirm that it's fine!

**Comment by browniebroke** [comment]
We also need to update the config for django-upgrade:

https://github.com/cookiecutter/cookiecutter-django/blob/master/{{cookiecutter.project_slug}}/.pre-commit-config.yaml#L31

**Review by browniebroke — APPROVED** [review]
We just need to update the config for django-upgrade:

https://github.com/cookiecutter/cookiecutter-django/blob/541ef05fc80706291ed1f4c0ca559ab73358eb97/%7B%7Bcookiecutter.project_slug%7D%7D/.pre-commit-config.yaml#L31

And the associated test:

https://github.com/cookiecutter/cookiecutter-django/blob/541ef05fc80706291ed1f4c0ca559ab73358eb97/tests/test_cookiecutter_generation.py#L232-L237

Other than that, it's good from my side.

**Comment by foarsitter** [comment]
Thanks for your feedback @browniebroke

**Pull request merged**
