### PR TITLE
Hides 'sign up' elements when ACCOUNT_ALLOW_REGISTRATION is disabled

### PR DESCRIPTION
**Pull request by wgordon17**
[//]: # (Thank you for helping us out: your efforts mean great deal to the project and the community as a whole!)

[//]: # (Before you proceed:)

[//]: # (1. Make sure to add yourself to `CONTRIBUTORS.rst` through this PR provided you're contributing here for the first time)
[//]: # (2. Don't forget to update the `docs/` presuming others would benefit from a concise description of whatever that you're proposing)

## Description

[//]: # (What's it you're proposing?)

I am proposing an update to whether or not the "Sign Up" links are shown when `ACCOUNT_ALLOW_REGISTRATION` is disabled for a project.

## Rationale

[//]: # (Why does the project need that?)

Currently, the "Sign Up" links still show, and end up linking immediately to a "Sign up is closed" page. This is a poor UX, and it would be nice to provide this out of the box.

## Use case(s) / visualization(s)

[//]: # ("Better to see something once than to hear about it a thousand times.")

Umm, same as above 👍

### CODE REVIEW

**Comment by wgordon17** [comment]
Screenshot of the proposed update to the signup page:

image

**Comment by demestav** [comment]
@wgordon17 the URLs are still active though, right?

**Comment by wgordon17** [comment]
@demestav You're referring to the /accounts/signup/ URL, correct? Yes, that link would still work...this just hides the visual elements and makes it much more obvious that Signup's are closed. Otherwise, user's would still see the Sign Up elements in the Nav and Sign In pages, which is just a poor UX IMO.

**Comment by demestav** [comment]
@wgordon17 Yes I agree with you. I was thinking that maybe it makes sense to remove the URLs as well to keep it consistent.

**Comment by wgordon17** [comment]
@demestav At the very least, we would still need the `/accounts/social/signup/` URL, because when using the social login, if the account doesn't already exist in the DB, then the user get's the Signup Closed page, which would be expected.

What's your preference? I'm good either way 👍

**Comment by demestav** [comment]
It would be better to wait from one of the maintainers to tell us their preference for the project. I was just commenting in case you missed it.

**Comment by wgordon17** [comment]
@demestav Agreed! Thanks for commenting 👍

**Review by browniebroke — APPROVED** [review]

**Pull request merged**
