### PR TITLE
Fix ungraceful Celery workers shutdown in container

### LINKED ISSUE #1743: docker-compose -f local.yml stop|down causes some containers to exit with code 137
## What happened?
Docker containers correctly initialized and running locally but a shutdown call exits with the attached log message.

Seems like the datastores (postgres, redis) respond to the SIGTERM but docker has to issue a SIGKILL to their dependents.

## What should've happened instead?
All containers exiting on SIGTERM with a non-error status code

## Steps to reproduce
Install new cookiecutter project following steps listed in docs, section - Getting Up and Running Locally With Docker .

[//]: # (Any or all of the following:)
[//]: # (* Host system configuration: OS, Docker & friends' versions etc.)
[//]: # (* Project generation options)
* Logs

```
cc_django_celerybeat_1 exited with code 137
cc_django_celeryworker_1 exited with code 137
redis_1         | 1:signal-handler (1533906750) Received SIGTERM scheduling shutdown...
cc_django_django_1 exited with code 137
postgres_1      | 2018-08-10 13:12:30.517 UTC [1] LOG:  received smart shutdown request
redis_1         | 1:M 10 Aug 13:12:30.517 # User requested shutdown...
redis_1         | 1:M 10 Aug 13:12:30.518 * Saving the final RDB snapshot before exiting.
redis_1         | 1:M 10 Aug 13:12:30.547 * DB saved on disk
redis_1         | 1:M 10 Aug 13:12:30.547 # Redis is now ready to exit, bye bye...
postgres_1      | 2018-08-10 13:12:30.552 UTC [1] LOG:  worker process: logical replication launcher (PID 30) exited with exit code 1
postgres_1      | 2018-08-10 13:12:30.553 UTC [25] LOG:  shutting down
postgres_1      | 2018-08-10 13:12:31.244 UTC [1] LOG:  database system is shut down
cc_django_redis_1 exited with code 0
cc_django_postgres_1 exited with code 0
```

### PR DESCRIPTION
**Pull request by goatwu1993**
## Description

Checklist:

- [x] I've made sure that `tests/test_cookiecutter_generation.py` is updated accordingly (especially if adding or updating a template option)
- [x] I've updated the documentation or confirm that my change doesn't require any updates

## Rationale

I use this awesome project to bootstrap a containerized Django + Celery application on AWS ECS.

I found out when I rolled upgrade Celery deployment in ECS, the old Celery pods shut down ungracefully. These old pods kept receiving tasks even if they are dying in the near future. Any ongoing tasks will then hang in some weird state.

Fix #1743 

## How to reproduce

- Create a project with celery and docker enabled
- Start the application
   ```bash
   docker-compose -f production.yml up --build
   ```
- Open another terminal to follow the logs of celery
   ```bash
   docker logs -f my_awesome_project_celeryworker_1
   ```
- Stop the container
   ```bash
   docker stop my_awesome_project_celeryworker_1
   ```
- See how the logs of celeryworker ended.

Expected
- Should see a warm shutdown in Celery log.

Reality
- Not logs showing warm shutdown. After the timeout, the container shut down ungracefully.

## How to Fix

- Add exec before celery

## Explanation

- In docker-compose,  kubectl, and AWS ECS, the way the Control pane gracefully shut down a container is
  1. Control pane send a SIGTERM
  2. The dying Application handles the SIGTERM by doing the unfinished tasks or sending the task back to the queue.
  3. Control pane send a SIGKILL If grace period exceeds (configurable, usually 30s to 60s) (Ungraceful shutdown)

- Celery has a built-in SIGTERM handling (although undocumented...), by doing the ongoing task or pushing the task into the queue and stopping receiving any new task.
- AWS Explanation for ECS: https://aws.amazon.com/blogs/containers/graceful-shutdowns-with-ecs/  
   Note: This is not ECS specific but also Kubernetes, docker, and docker-compose. I paste this page only because it is easier to read.

## Some screenshots

Without graceful shutdown
Screen Shot 2021-11-15 at 2 29 31 PM

With graceful shutdown

Screen Shot 2021-11-15 at 2 30 51 PM

### CODE REVIEW

**Comment by foarsitter** [comment]
Thank you for your clear and well explained pull request!

**Review by browniebroke — APPROVED** [review]
Nice one! 

I think this was reported as an issue locally - see #1743 - but we since switched to a different command to watch for changes, and it might be fine now. However, we use a [similar command for the `beat` process](https://github.com/cookiecutter/cookiecutter-django/blob/8778cfccc1a7a3ff17f374e79386c7bf47cf6aef/%7B%7Bcookiecutter.project_slug%7D%7D/compose/production/django/celery/beat/start?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L8), should we also prefix it with `exec`?

**Comment by goatwu1993** [comment]
OBH, I am not very familiar with celery beats.

However, my guess is
- All the celery beat does is produce tasks to the queue periodically, which should be pretty fast (under good networking).
- All scheduled tasks are stored in the Django database(as they advertised).

As a result, whether Celery Beat shut down gracefully or not should not matter as much as Celery's worker.

Still, I do some tests. The only observable change is the docker stop command takes less time (10s -> 0.7s), which is as expected since the Celery main process receives a SIGTERM it just exits without extra handling. 

It still makes sense to add exec at the front for celery beat since this way SIGTERM is passed to celery makes pod get stoped/deleted faster. This will make service upgrades/shutdown faster in some circumstances.

**Comment by browniebroke** [comment]
Yes, I see, makes sense. I'm happy to accept this as is, since workers are the most visible issue, but I'll leave this open for a bit to give you time to adjust it if you want.

**Comment by goatwu1993** [comment]
I take a look at celery flower and seems that celery flower has a dummy [SIGTERM handling](https://github.com/mher/flower/blob/af9ae380c8f53a0152486b3372b27b83198c8d51/flower/command.py#L46) as well. Not sure whether flower will implement some logic in the future. Should test flower for playing safe for the future.

I guess I would not able to see the log in the current script. I will add exec and test tomorrow with my laptop. If the logs change and beat/flower live happy and alive, I will commit another change.

**Comment by goatwu1993** [comment]
The `exec` should be added to beat and flower as discussed above. Updated and ready to merge

Before
Screen Shot 2021-11-16 at 10 15 32 AM
Screen Shot 2021-11-16 at 10 18 34 AM

**Comment by goatwu1993** [comment]
Installed **procps** and check ps output to double confirm. Celery main process is not forked from the script, being PID 1 so it can receive SIGTERM as expected.

Before
Screen Shot 2021-11-16 at 10 29 15 AM

After
Screen Shot 2021-11-16 at 10 27 57 AM

**Comment by browniebroke** [comment]
Thanks for this fix! 🎉

**Pull request merged**
