### PR TITLE
Fix celery beat startup without `django_celery_beat` tables

### LINKED ISSUE #2727: Race condition causing celerybeat and celeryworker to fail
## What happened?

There is a race condition where `celerybeat` and/or `celeryworker` services will fail to start if the `django-celery-beat` migrations have not run. Bringing up the stack up again once those migrations have run will resume normally as expected.

## What should've happened instead?

While this can only occur under specific conditions (usually first run), it is best to have a guarantee that all services will be up and running 100% out-of-the-box. The `celerybeat` and/or `celeryworker` services should have a health check in its entrypoint script prior to running its command script. I personally have some code for this if you guys are interested, but I want to hear your thoughts first.

## Steps to reproduce

Tested on Ubuntu 18.04.4 LTS, Docker Engine version 19.03.12, docker-compose version 1.17.1

1. Create a new project from this template as you normally would but with docker and celery support.
2. Build and bring the whole stack up. The race condition usually shows up for me on the first run.
3. If it did not trigger the first time, then drop the database volume, and bring up the stack. You may need to repeat this step multiple times. 

## Some screenshots

image

image

### PR DESCRIPTION
**Pull request by goatwu1993**
## Description

run `python manage.py migrate django_celery_beat`, make sure the necessary table exists before celery beat startup. 

Checklist:

- [ ] I've made sure that tests are updated accordingly (especially if adding or updating a template option)
- [ ] I've updated the documentation or confirm that my change doesn't require any updates

## Rationale

Fix #2727

tested by `docker-compose -f ./local.yml up celerybeat --build`

Before:
Screenshot 2023-07-14 at 2 46 54 PM

After:
Screenshot 2023-07-14 at 2 47 00 PM

### CODE REVIEW

**Review by auvipy — APPROVED** [review]
that is good

**Comment by browniebroke** [comment]
The only thing that I is holding me back from merging this is that I wanted to see is what happens if I run:

```
docker-compose -f ./local.yml up --build
```

I think that both the `celerybeat` and `django` will try to run migrations, and depending on timing, they may step on each other. Has anyone tried this?

**Comment by foarsitter** [comment]
Running the migrations for `celerybeat` is part of the setup of `celerybeat`. The error's are very clear when there is a table missing. So for me this is of little value.

**Review by browniebroke — CHANGES_REQUESTED** [review]
I just tried this and I confirmed my suspicion: it breaks spectacularly if you start multiple services with `docker compose -f local.yml up --build`. I _think_ both the `beat` service and `django` sevice are competing to run the migrations, which leads to some weird errors.


<details>
<summary>

Logs

</summary>

```
browniebrokenofe_local_django        | Operations to perform:
browniebrokenofe_local_django        |   Apply all migrations: account, admin, auth, contenttypes, django_celery_beat, sessions, sites, socialaccount, users
browniebrokenofe_local_django        | Running migrations:
browniebrokenofe_local_django        |   Applying contenttypes.0001_initial... OK
browniebrokenofe_local_django        |   Applying contenttypes.0002_remove_content_type_name... OK
browniebrokenofe_local_celerybeat    | Operations to perform:
browniebrokenofe_local_celerybeat    |   Apply all migrations: django_celery_beat
browniebrokenofe_local_celerybeat    | Running migrations:
browniebrokenofe_local_celerybeat    |   Applying django_celery_beat.0001_initial... OK
browniebrokenofe_local_django        |   Applying auth.0001_initial... OK
browniebrokenofe_local_django        |   Applying auth.0002_alter_permission_name_max_length... OK
browniebrokenofe_local_celerybeat    |   Applying django_celery_beat.0002_auto_20161118_0346... OK
browniebrokenofe_local_django        |   Applying auth.0003_alter_user_email_max_length... OK
browniebrokenofe_local_celerybeat    |   Applying django_celery_beat.0003_auto_20161209_0049... OK
browniebrokenofe_local_django        |   Applying auth.0004_alter_user_username_opts... OK
browniebrokenofe_local_celerybeat    |   Applying django_celery_beat.0004_auto_20170221_0000... OK
browniebrokenofe_local_django        |   Applying auth.0005_alter_user_last_login_null... OK
browniebrokenofe_local_celerybeat    |   Applying django_celery_beat.0005_add_solarschedule_events_choices... OK
browniebrokenofe_local_django        |   Applying auth.0006_require_contenttypes_0002... OK
browniebrokenofe_local_django        |   Applying auth.0007_alter_validators_add_error_messages... OK
browniebrokenofe_local_django        |   Applying auth.0008_alter_user_username_max_length... OK
browniebrokenofe_local_django        |   Applying auth.0009_alter_user_last_name_max_length... OK
browniebrokenofe_local_celerybeat    |   Applying django_celery_beat.0006_auto_20180322_0932... OK
browniebrokenofe_local_django        |   Applying auth.0010_alter_group_name_max_length... OK
browniebrokenofe_local_django        |   Applying auth.0011_update_proxy_permissions... OK
browniebrokenofe_local_django        |   Applying auth.0012_alter_user_first_name_max_length... OK
browniebrokenofe_local_celerybeat    |   Applying django_celery_beat.0007_auto_20180521_0826... OK
browniebrokenofe_local_celerybeat    |   Applying django_celery_beat.0008_auto_20180914_1922... OK
browniebrokenofe_local_celerybeat    |   Applying django_celery_beat.0006_auto_20180210_1226... OK
browniebrokenofe_local_celerybeat    |   Applying django_celery_beat.0006_periodictask_priority... OK
browniebrokenofe_local_celerybeat    |   Applying django_celery_beat.0009_periodictask_headers... OK
browniebrokenofe_local_django        |   Applying users.0001_initial... OK
browniebrokenofe_local_django        |   Applying account.0001_initial... OK
browniebrokenofe_local_django        |   Applying account.0002_email_max_length... OK
browniebrokenofe_local_django        |   Applying account.0003_alter_emailaddress_create_unique_verified_email... OK
browniebrokenofe_local_django        |   Applying account.0004_alter_emailaddress_drop_unique_email... OK
browniebrokenofe_local_django        |   Applying account.0005_emailaddress_idx_upper_email... OK
browniebrokenofe_local_celerybeat    |   Applying django_celery_beat.0010_auto_20190429_0326... OK
browniebrokenofe_local_celerybeat    |   Applying django_celery_beat.0011_auto_20190508_0153... OK
browniebrokenofe_local_celerybeat    |   Applying django_celery_beat.0012_periodictask_expire_seconds... OK
browniebrokenofe_local_celerybeat    |   Applying django_celery_beat.0013_auto_20200609_0727... OK
browniebrokenofe_local_celerybeat    |   Applying django_celery_beat.0014_remove_clockedschedule_enabled... OK
browniebrokenofe_local_celerybeat    |   Applying django_celery_beat.0015_edit_solarschedule_events_choices... OK
browniebrokenofe_local_django        |   Applying admin.0001_initial... OK
browniebrokenofe_local_celerybeat    |   Applying django_celery_beat.0016_alter_crontabschedule_timezone... OK
browniebrokenofe_local_celerybeat    |   Applying django_celery_beat.0017_alter_crontabschedule_month_of_year... OK
browniebrokenofe_local_django        |   Applying admin.0002_logentry_remove_auto_add... OK
browniebrokenofe_local_celerybeat    |   Applying django_celery_beat.0018_improve_crontab_helptext... OK
browniebrokenofe_local_django        |   Applying admin.0003_logentry_add_action_flag_choices... OK
browniebrokenofe_local_postgres      | 2024-01-20 14:00:03.522 UTC [72] ERROR:  relation "django_celery_beat_crontabschedule" already exists
browniebrokenofe_local_postgres      | 2024-01-20 14:00:03.522 UTC [72] STATEMENT:  CREATE TABLE "django_celery_beat_crontabschedule" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "minute" varchar(64) NOT NULL, "hour" varchar(64) NOT NULL, "day_of_week" varchar(64) NOT NULL, "day_of_month" varchar(64) NOT NULL, "month_of_year" varchar(64) NOT NULL)
browniebrokenofe_local_django        | Traceback (most recent call last):
browniebrokenofe_local_postgres      | 2024-01-20 14:00:03.527 UTC [73] ERROR:  column django_content_type.name does not exist at character 36
browniebrokenofe_local_celerybeat    | Traceback (most recent call last):
browniebrokenofe_local_flower        | INFO 2024-01-20 14:00:03,534 command 9 281473084223520 Visit me at http://0.0.0.0:5555
browniebrokenofe_local_django        |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
browniebrokenofe_local_postgres      | 2024-01-20 14:00:03.527 UTC [73] STATEMENT:  SELECT "django_content_type"."id", "django_content_type"."name", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'contenttypes' ORDER BY "django_content_type"."name" ASC
browniebrokenofe_local_celerybeat    |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
browniebrokenofe_local_django        |     return self.cursor.execute(sql)
browniebrokenofe_local_django        |            ^^^^^^^^^^^^^^^^^^^^^^^^
browniebrokenofe_local_django        |   File "/usr/local/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute
browniebrokenofe_local_celerybeat    |     return self.cursor.execute(sql, params)
browniebrokenofe_local_celerybeat    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browniebrokenofe_local_celerybeat    |   File "/usr/local/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute
browniebrokenofe_local_celerybeat    |     raise ex.with_traceback(None)
browniebrokenofe_local_celerybeat    | psycopg.errors.UndefinedColumn: column django_content_type.name does not exist
browniebrokenofe_local_celerybeat    | LINE 1: SELECT "django_content_type"."id", "django_content_type"."na...
browniebrokenofe_local_celerybeat    |                                            ^
browniebrokenofe_local_django        |     raise ex.with_traceback(None)
browniebrokenofe_local_celerybeat    | 
browniebrokenofe_local_celerybeat    | The above exception was the direct cause of the following exception:
browniebrokenofe_local_django        | psycopg.errors.DuplicateTable: relation "django_celery_beat_crontabschedule" already exists
browniebrokenofe_local_django        | 
browniebrokenofe_local_celerybeat    | 
browniebrokenofe_local_django        | The above exception was the direct cause of the following exception:
browniebrokenofe_local_celerybeat    | Traceback (most recent call last):
browniebrokenofe_local_django        | 
browniebrokenofe_local_celerybeat    |   File "/app/manage.py", line 31, in <module>
browniebrokenofe_local_django        | Traceback (most recent call last):
browniebrokenofe_local_celerybeat    |     execute_from_command_line(sys.argv)
browniebrokenofe_local_celerybeat    |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
browniebrokenofe_local_celerybeat    |     utility.execute()
browniebrokenofe_local_celerybeat    |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
browniebrokenofe_local_celerybeat    |     self.fetch_command(subcommand).run_from_argv(self.argv)
browniebrokenofe_local_celerybeat    |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
browniebrokenofe_local_celerybeat    |     self.execute(*args, **cmd_options)
browniebrokenofe_local_celerybeat    |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
browniebrokenofe_local_celerybeat    |     output = self.handle(*args, **options)
browniebrokenofe_local_django        |   File "/app/manage.py", line 31, in <module>
browniebrokenofe_local_django        |     execute_from_command_line(sys.argv)
browniebrokenofe_local_django        |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
browniebrokenofe_local_django        |     utility.execute()
browniebrokenofe_local_django        |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
browniebrokenofe_local_celerybeat    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browniebrokenofe_local_django        |     self.fetch_command(subcommand).run_from_argv(self.argv)
browniebrokenofe_local_django        |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
browniebrokenofe_local_django        |     self.execute(*args, **cmd_options)
browniebrokenofe_local_celerybeat    |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
browniebrokenofe_local_celerybeat    |     res = handle_func(*args, **kwargs)
browniebrokenofe_local_celerybeat    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browniebrokenofe_local_celerybeat    |   File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 383, in handle
browniebrokenofe_local_celerybeat    |     emit_post_migrate_signal(
browniebrokenofe_local_celerybeat    |   File "/usr/local/lib/python3.11/site-packages/django/core/management/sql.py", line 52, in emit_post_migrate_signal
browniebrokenofe_local_celerybeat    |     models.signals.post_migrate.send(
browniebrokenofe_local_django        |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
browniebrokenofe_local_celerybeat    |   File "/usr/local/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send
browniebrokenofe_local_django        |     output = self.handle(*args, **options)
browniebrokenofe_local_django        |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browniebrokenofe_local_django        |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
browniebrokenofe_local_celerybeat    |     return [
browniebrokenofe_local_celerybeat    |            ^
browniebrokenofe_local_celerybeat    |   File "/usr/local/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
browniebrokenofe_local_celerybeat    |     (receiver, receiver(signal=self, sender=sender, **named))
browniebrokenofe_local_django        |     res = handle_func(*args, **kwargs)
browniebrokenofe_local_celerybeat    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browniebrokenofe_local_django        |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browniebrokenofe_local_django        |   File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 356, in handle
browniebrokenofe_local_django        |     post_migrate_state = executor.migrate(
browniebrokenofe_local_celerybeat    |   File "/usr/local/lib/python3.11/site-packages/django/contrib/auth/management/__init__.py", line 51, in create_permissions
browniebrokenofe_local_celerybeat    |     create_contenttypes(
browniebrokenofe_local_celerybeat    |   File "/usr/local/lib/python3.11/site-packages/django/contrib/contenttypes/management/__init__.py", line 127, in create_contenttypes
browniebrokenofe_local_celerybeat    |     content_types, app_models = get_contenttypes_and_models(
browniebrokenofe_local_django        |                          ^^^^^^^^^^^^^^^^^
browniebrokenofe_local_celerybeat    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browniebrokenofe_local_flower        | INFO 2024-01-20 14:00:03,539 command 9 281473084223520 Broker: redis://redis:6379/0
browniebrokenofe_local_django        |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 135, in migrate
browniebrokenofe_local_django        |     state = self._migrate_all_forwards(
browniebrokenofe_local_django        |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
browniebrokenofe_local_django        |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
browniebrokenofe_local_django        |     state = self.apply_migration(
browniebrokenofe_local_django        |             ^^^^^^^^^^^^^^^^^^^^^
browniebrokenofe_local_django        |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
browniebrokenofe_local_django        |     state = migration.apply(state, schema_editor)
browniebrokenofe_local_celerybeat    |   File "/usr/local/lib/python3.11/site-packages/django/contrib/contenttypes/management/__init__.py", line 98, in get_contenttypes_and_models
browniebrokenofe_local_celerybeat    |     content_types = {
browniebrokenofe_local_celerybeat    |                     ^
browniebrokenofe_local_celerybeat    |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 398, in __iter__
browniebrokenofe_local_celerybeat    |     self._fetch_all()
browniebrokenofe_local_celerybeat    |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
browniebrokenofe_local_celerybeat    |     self._result_cache = list(self._iterable_class(self))
browniebrokenofe_local_celerybeat    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browniebrokenofe_local_celerybeat    |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
browniebrokenofe_local_celerybeat    |     results = compiler.execute_sql(
browniebrokenofe_local_celerybeat    |               ^^^^^^^^^^^^^^^^^^^^^
browniebrokenofe_local_celerybeat    |   File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
browniebrokenofe_local_celerybeat    |     cursor.execute(sql, params)
browniebrokenofe_local_celerybeat    |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
browniebrokenofe_local_celerybeat    |     return super().execute(sql, params)
browniebrokenofe_local_django        |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browniebrokenofe_local_django        |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/migration.py", line 132, in apply
browniebrokenofe_local_django        |     operation.database_forwards(
browniebrokenofe_local_django        |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/operations/models.py", line 96, in database_forwards
browniebrokenofe_local_django        |     schema_editor.create_model(model)
browniebrokenofe_local_django        |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 451, in create_model
browniebrokenofe_local_django        |     self.execute(sql, params or None)
browniebrokenofe_local_django        |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/postgresql/schema.py", line 45, in execute
browniebrokenofe_local_django        |     return super().execute(sql, params)
browniebrokenofe_local_celerybeat    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browniebrokenofe_local_celerybeat    |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
browniebrokenofe_local_celerybeat    |     return self._execute_with_wrappers(
browniebrokenofe_local_celerybeat    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browniebrokenofe_local_celerybeat    |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
browniebrokenofe_local_celerybeat    |     return executor(sql, params, many, context)
browniebrokenofe_local_celerybeat    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browniebrokenofe_local_celerybeat    |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
browniebrokenofe_local_celerybeat    |     with self.db.wrap_database_errors:
browniebrokenofe_local_django        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browniebrokenofe_local_flower        | INFO 2024-01-20 14:00:03,541 command 9 281473084223520 Registered tasks: 
browniebrokenofe_local_flower        | ['browniebrokenofe.users.tasks.get_users_count',
browniebrokenofe_local_flower        |  'celery.accumulate',
browniebrokenofe_local_flower        |  'celery.backend_cleanup',
browniebrokenofe_local_flower        |  'celery.chain',
browniebrokenofe_local_flower        |  'celery.chord',
browniebrokenofe_local_flower        |  'celery.chord_unlock',
browniebrokenofe_local_celerybeat    |   File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
browniebrokenofe_local_celerybeat    |     raise dj_exc_value.with_traceback(traceback) from exc_value
browniebrokenofe_local_celerybeat    |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
browniebrokenofe_local_django        |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 201, in execute
browniebrokenofe_local_flower        |  'celery.chunks',
browniebrokenofe_local_flower        |  'celery.group',
browniebrokenofe_local_flower        |  'celery.map',
browniebrokenofe_local_flower        |  'celery.starmap']
browniebrokenofe_local_flower        | INFO 2024-01-20 14:00:03,550 mixins 9 281472993391008 Connected to redis://redis:6379/0
browniebrokenofe_local_celerybeat    |     return self.cursor.execute(sql, params)
browniebrokenofe_local_celerybeat    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browniebrokenofe_local_celerybeat    |   File "/usr/local/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute
browniebrokenofe_local_celerybeat    |     raise ex.with_traceback(None)
browniebrokenofe_local_django        |     cursor.execute(sql, params)
browniebrokenofe_local_django        |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
browniebrokenofe_local_django        |     return super().execute(sql, params)
browniebrokenofe_local_django        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browniebrokenofe_local_django        |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
browniebrokenofe_local_django        |     return self._execute_with_wrappers(
browniebrokenofe_local_django        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browniebrokenofe_local_django        |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
browniebrokenofe_local_django        |     return executor(sql, params, many, context)
browniebrokenofe_local_celerybeat    | django.db.utils.ProgrammingError: column django_content_type.name does not exist
browniebrokenofe_local_celerybeat    | LINE 1: SELECT "django_content_type"."id", "django_content_type"."na...
browniebrokenofe_local_celerybeat    |                                            ^
browniebrokenofe_local_django        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
browniebrokenofe_local_django        |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
browniebrokenofe_local_django        |     with self.db.wrap_database_errors:
browniebrokenofe_local_django        |   File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
browniebrokenofe_local_django        |     raise dj_exc_value.with_traceback(traceback) from exc_value
browniebrokenofe_local_django        |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
browniebrokenofe_local_django        |     return self.cursor.execute(sql)
browniebrokenofe_local_django        |            ^^^^^^^^^^^^^^^^^^^^^^^^
browniebrokenofe_local_django        |   File "/usr/local/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute
browniebrokenofe_local_django        |     raise ex.with_traceback(None)
browniebrokenofe_local_django        | django.db.utils.ProgrammingError: relation "django_celery_beat_crontabschedule" already exists
browniebrokenofe_local_django        |   Applying django_celery_beat.0001_initial...
browniebrokenofe_local_celeryworker  | /usr/local/lib/python3.11/site-packages/celery/platforms.py:829: SecurityWarning: You're running the worker with superuser privileges: this is
browniebrokenofe_local_celeryworker  | absolutely not recommended!
browniebrokenofe_local_celeryworker  | 
browniebrokenofe_local_celeryworker  | Please specify a different user using the --uid option.
browniebrokenofe_local_celeryworker  | 
browniebrokenofe_local_celeryworker  | User information: uid=0 euid=0 gid=0 egid=0
browniebrokenofe_local_celeryworker  | 
browniebrokenofe_local_celeryworker  |   warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
browniebrokenofe_local_celeryworker  |  
browniebrokenofe_local_celeryworker  |  -------------- celery@0291e25f3a48 v5.3.6 (emerald-rush)
browniebrokenofe_local_celeryworker  | --- ***** ----- 
browniebrokenofe_local_celeryworker  | -- ******* ---- Linux-6.5.11-linuxkit-aarch64-with-glibc2.36 2024-01-20 14:00:03
browniebrokenofe_local_celeryworker  | - *** --- * --- 
browniebrokenofe_local_celeryworker  | - ** ---------- [config]
browniebrokenofe_local_celeryworker  | - ** ---------- .> app:         browniebrokenofe:0xffff7f746290
browniebrokenofe_local_celeryworker  | - ** ---------- .> transport:   redis://redis:6379/0
browniebrokenofe_local_celeryworker  | - ** ---------- .> results:     redis://redis:6379/0
browniebrokenofe_local_celeryworker  | - *** --- * --- .> concurrency: 10 (prefork)
browniebrokenofe_local_celeryworker  | -- ******* ---- .> task events: ON
browniebrokenofe_local_celeryworker  | --- ***** ----- 
browniebrokenofe_local_celeryworker  |  -------------- [queues]
browniebrokenofe_local_celeryworker  |                 .> celery           exchange=celery(direct) key=celery
browniebrokenofe_local_celeryworker  |                 
browniebrokenofe_local_celeryworker  | 
browniebrokenofe_local_celeryworker  | [tasks]
browniebrokenofe_local_celeryworker  |   . browniebrokenofe.users.tasks.get_users_count
browniebrokenofe_local_celeryworker  | 
browniebrokenofe_local_django exited with code 1
browniebrokenofe_local_celerybeat exited with code 1
```

</details>

If you look at the logs, there is a mix of "relation does not exist" and "releation already exists" which is pretty confusing. 

I agree that the current error message is much clearer that what we get after this change, so I'm against this change, which is a step back IMO.

**Comment by Andrew-Chen-Wang** [comment]
perhaps an easier solution is to create a pid/lock file? In the start/entrypoint command for local scripts only, if a script needs to run migrations, it creates a migration.pid that is gitignored. If another migration.pid exists, continuously wait 1 second until it disappears. After a migration delete the pid file.

**Comment by foarsitter** [comment]
If this was a real issue you provided a real solution @Andrew-Chen-Wang, but for me it feels like over engineering since we are talking about a dev environment. 

An other solution comes to my mind is to create a third container for the migrations an let it exit afterwards and then start django related containers. But then again, it creates more problems then it solves I supose.

**Comment by browniebroke** [comment]
> perhaps an easier solution is to create a pid/lock file? In the start/entrypoint command for local scripts only, if a script needs to run migrations, it creates a migration.pid that is gitignored. If another migration.pid exists, continuously wait 1 second until it disappears. After a migration delete the pid file.

Yes, I was thinking about that, however we need to make it reliable. For example, what happens if the migration process crashes or is interrupted in the middle and the lock file is not removed? Could there be a race condition where the 2 processes write the file at the same time?

> An other solution comes to my mind is to create a third container for the migrations an let it exit afterwards and then start django related containers.

👍🏻 

> for me it feels like over engineering since we are talking about a dev environment.

💯

**Comment by foarsitter** [comment]
Closing this as not planned.

**Pull request closed without merging**
