### PR TITLE
Add  support for drone.io (Fix #2082)

### LINKED ISSUE #2082: Add support for drone.io
## Description
Drone.io support built-in
[//]: # (What's it you're proposing? How should it be implemented?)
Add a .drone.yml file that allows projects to be tested/built using drone.io

## Rationale

[//]: # (Why should this feature be implemented?)
There are options for several areas of the project. Why not add some more flavor to the CI/CD options?
[Drone ](https://github.com/drone/drone) is very nice, from what I have tested. Also, it is open source, unlike most solutions out there. This makes it a candidate for baseline support.

## Use case(s) / visualization(s)

[//]: # ("Better to see something once than to hear about it a thousand times.")
Same as travis, actually. Adding some more options to people who uses other tools. This could be selected at install time.

### PR DESCRIPTION
**Pull request by shywn-mrk**
## Description
Added Drone CI support and configuration.

Checklist:

- [x] I've added the option to choose Drone as the CI tool.
- [x] I've updated the documentation.
- [x] I've made sure that the config file is deleted when Drone is not selected.
- [x] I've added the Drone config file. 

## Rationale
Fix #2082

### CODE REVIEW

**Comment by shywn-mrk** [comment]
@browniebroke You're welcome! At this moment, unfortunately, no. But still trying to understand a way to somehow figure it out.

**Comment by browniebroke** [comment]
Are there any update on this? If not, I'm happy to accept it as community contributed as is. It's very much self-contained and easy to remove if we change our mind.

**Comment by shywn-mrk** [comment]
@browniebroke Right now I don't have any updates, but at that moment I checked for some static analyzing tools to ensure that the outputted syntax is correct but didn't find much. If I find anything I'll definitely inform you and support any changes. If it's possible for you to merge, I'll be happy. And actually, this if my first open-source contribution. :)

**Comment by browniebroke** [comment]
Ok, let's get it out, we might get some feedback from people using it, and it shouldn't impact those who don't.

**Pull request merged**
