### PR TITLE
Update postgres versions

### PR DESCRIPTION
**Pull request by Afrowave**
This pull request updates the Postgres database versions of choice. 

## Checklist:

- [x] I've made sure that tests are updated accordingly (especially if adding or updating a template option)
- [x] I've updated the documentation or confirm that my change doesn't require any updates

## Rationale

It would be nice for those starting a new project to start with the last fixes to the "The World's Most Advanced Open Source Relational Database". To do this, we have left only the major versions as the database choices so that the latest of the versions from the Docker hub is pulled.

We have also changed the possible output on the README as a guide.

This resolves #3711.

### CODE REVIEW

**Comment by Afrowave** [comment]
I was busy wringing my hands. That checklist is important! Thank you @browniebroke. 😃

**Comment by browniebroke** [comment]
Did you really intended to close this pull request? It looks good to me...

**Comment by Afrowave** [comment]
Oh no. It is good. I must have closed the wrong one. I need to be more careful when deleting branches from my local dev.

**Comment by browniebroke** [comment]
Thanks!

**Pull request merged**
