### PR TITLE
Replace deprecated `uvicorn.workers` with `uvicorn-worker`

### LINKED ISSUE #5109: `uvicorn.workers` is deprecated
According to https://github.com/encode/uvicorn/pull/2302 and https://github.com/cookiecutter/cookiecutter-django/pull/5101 `uvicorn.workers` is deprecated. 

It should be rather an easy task to update to `uvicorn-worker`.

### PR DESCRIPTION
**Pull request by jasonmokk**
## Description
This PR replaces all references to the deprecated `uvicorn.workers` module in favor of `uvicorn-worker`. 

Closes #5109 

Checklist:

- [ ] I've made sure that tests are updated accordingly (especially if adding or updating a template option)
- [ ] I've updated the documentation or confirm that my change doesn't require any updates

### CODE REVIEW

**Comment by foarsitter** [comment]
@jasonmokk, did you test this change in your local environment?

**Comment by jasonmokk** [comment]
> @jasonmokk, did you test this change in your local environment?

Yes, all tests are passing locally. 
Screenshot 2024-05-31 at 11 58 47
Screenshot 2024-05-31 at 12 00 35

**Comment by foarsitter** [comment]
Your modification isn't covered by the test-suite. I can tell you right away this wont work because you didn't install the package and your worker class contains an hyphen, which is not allowed in Python.

**Comment by jasonmokk** [comment]
Thank you for the feedback. I installed the `uvicorn-worker` package and added it to the `requirements.txt` file. I also corrected the worker class name to `uvicorn_worker` and tests are passing. My apologies for the misunderstanding with the tests, this time I correctly used Docker on my mac machine and tests are passing.

**Comment by browniebroke** [comment]
The automated test suite of the generated project isn't covering uvicorn either, it's only used when starting the server with the unicorn commands, in the files that you changed.

**Review by browniebroke — APPROVED** [review]

**Comment by browniebroke** [comment]
Thanks for the contribution!

**Pull request merged**
